export const UPDATE_FILTERS = 'UPDATE_FILTERS';
export const UPDATE_FILTERS_SET_ALL = 'UPDATE_FILTERS_SET_ALL';
export const UPDATE_SORT = 'UPDATE_SORT';

export const GET_SEARCH_ID_START = 'GET_SEARCH_ID_START';
export const GET_SEARCH_ID_SUCCESS = 'GET_SEARCH_ID_SUCCESS';
export const GET_SEARCH_ID_FAILURE = 'GET_SEARCH_ID_FAILURE';

export const FETCH_TICKETS_START = 'FETCH_TICKETS_START';
export const FETCH_TICKETS_SUCCESS = 'FETCH_TICKETS_SUCCESS';
export const FETCH_TICKETS_FAILURE = 'FETCH_TICKETS_FAILURE';

export const FETCH_TICKETS_STOPPED = 'FETCH_TICKETS_STOPPED';

export const INIT_TICKETS_OFFSET = 'INIT_TICKETS_OFFSET';
export const RESET_TICKETS_OFFSET = 'RESET_TICKETS_OFFSET';

export const LOAD_MORE_TICKETS = 'LOAD_MORE_TICKETS';

export const HIDE_ERROR = 'HIDE_ERROR';
